# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    dump:
        class: Symfony\Component\VarDumper\VarDumper  
    foo:
        class: Beluha\AppBundle\Service\FooService
        ###arguments: ["@dump"]
        arguments: ["@request_stack"]
        #calls:
            #- [setContainer, ["@service_container"]]
        #calls:
            #- [setDumper, ["@dump"]]
        ###tags:
            ###- {name: monolog.logger}
    
    #added_quote:
        #class: Beluha\StoreBundle\Entity\Quote
        #calls:
            #- [setByAdded, ["@service_container"]]
        #public: false
    #smtc.main.form.autocomplete_entity_type:
        #class: Beluha\StoreBundle\Form\QuoteType
        #arguments: ["@doctrine.orm.entity_manager"]
        #tags:
            #- {name: form.type, alias: autocomplete_entity}
    app.login_menu_builder:
        class: Beluha\StoreBundle\Menu\LoginMenuBuilder
        arguments: ["@knp_menu.factory", "@service_container"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: login }