<?php

namespace Beluha\BlogBundle\Repository;

use Symfony\Component\VarDumper\VarDumper;

/**
 * AuthorQuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorQuoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTerm($term)
    {
        $dumper = new VarDumper();
        $q = $this->getEntityManager()
            ->createQuery('SELECT a FROM BeluhaBlogBundle:AuthorQuote a WHERE a.name LIKE :name')
            ->setParameter('name', '%'.$term.'%');
        $dumper->dump($q);
        
        return $q->getResult();
        /*return $this->getEntityManager()
            ->createQuery('SELECT a FROM BeluhaBlogBundle:AuthorQuote a WHERE a.name LIKE :name')
            ->setParameter('name', $term.'%')
            ->getResult();*/
    }
}
