<?php

namespace Beluha\BlogBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find latest
     * 
     * @param int $num How many posts to get
     * @return array
     */
    public function findLatest($num)
    {
        $qb = $this->getQueryBilder()
                ->orderBy('p.createdAt','desc')
                ->setMaxResults($num);
        return $qb->getQuery()->getResult();
    }
    
    /**
     * Find first post
     * 
     * @return Post
     */
    public function findFirst()
    {
        $qb =  $this->getQueryBilder()
                ->orderBy('p.id', 'asc')
                ->setMaxResults(1);
        
        return $qb->getQuery()->getSingleResult();
    }
    
    private function getQueryBilder()
    {
        $em = $this->getEntityManager();
        $qb = $em->getRepository('BeluhaBlogBundle:Post')->createQueryBuilder('p');
        return $qb;
    }
    
}
