Beluha_store_homepage:
    path:     /
    defaults: { _controller: BeluhaStoreBundle:Default:index }
Beluha_store_create:
    path:     /create
    defaults: { _controller: BeluhaStoreBundle:Default:create }
Beluha_store_show:
    path:     /show/{id}
    defaults: { _controller: BeluhaStoreBundle:Default:show }
    requirements:
        id: \d+
Beluha_store_update:
    path:     /update/{id}
    defaults: { _controller: BeluhaStoreBundle:Default:update }
    requirements:
        id: \d+        
Beluha_store_fun:
    path:     /fun/{number}.{_format}
    defaults: { _controller: BeluhaStoreBundle:Fun:index, number:7}
Beluha_store_advanced:
    path: /advanced/{year}/{culture}/{title}.{_format}
    defaults: {_controller: BeluhaStoreBundle:Advanced:advanced}
    requirements:
        culture: ru|en
        year: \d+
        _format: html|php
